### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by agatafilipczak**
added loops for altering structure of db and importing additional label data to variable table

### CODE REVIEW

**Comment by tzok** [comment]
@agatafilipczak It means that we need to load `catalog_qt_2/sql/schema/{a,d}_*.sql` to the database, right? 

If yes, then the following should be applied for the Docker Compose image I believe:
```diff
diff --git a/docker-compose/build/Dockerfile b/docker-compose/build/Dockerfile
index 8464e20..4246933 100644
--- a/docker-compose/build/Dockerfile
+++ b/docker-compose/build/Dockerfile
@@ -3,14 +3,14 @@ FROM imas/ual AS ual
 COPY catalog_qt_2/sql/feed/imas/dumpSummaryFieldsSQL.xsl /tmp/dumpSummaryFieldsSQL.xsl

 RUN echo 'USE itm_catalog_qt' > /tmp/20-variables.sql && \
-    xsltproc /tmp/dumpSummaryFieldsSQL.xsl /opt/imas/core/IMAS/*/include/IDSDef.xml >> /tmp/20-variables.sql
+    xsltproc /tmp/dumpSummaryFieldsSQL.xsl /opt/imas/core/IMAS/*/include/IDSDef.xml >> /tmp/z_001_variables.sql

 ################################################################################

 FROM mariadb AS db

-COPY catalog_qt_2/sql/schema/catalog_qt_db.sql /docker-entrypoint-initdb.d/10-schema.sql
-COPY --from=ual /tmp/20-variables.sql /docker-entrypoint-initdb.d/20-variables.sql
+COPY catalog_qt_2/sql/schema/*.sql /docker-entrypoint-initdb.d/
+COPY --from=ual /tmp/z_001_variables.sql /docker-entrypoint-initdb.d/
```

**Comment by mkopsnc** [comment]
In fact, it's little bit more complicated.

We have two kinds of updates for database. Ones (prefixed with `a_` - for alter) that are supposed to be run after database is created. These updates will affect only database structure.

We also have another set of updates (prefixed with `d_` - for data) that are supposed to be run once database is already filled with variables. These updates may alter the data (for example we want to change some fields in database - e.g. dictionaries).

I guess, we have to change docker compose based approach a little bit.

And, final comment. Bartek is working on adapting docker compose based installation to OpenShift. Here, we have another issue:

- we should not use root at all
- we can't store data in `/` and `/root` directly

This is why Bartek is changing build process such way everything is run as user `imas` and all the components are installed inside `/home/imas/opt`.

This is a limitation based on OpenShift's requirements.

**Comment by agatafilipczak** [comment]
@tzok  I don't know how the docker compose's Dockerfile should work, but what I was trying to maintain is:

- load the the main sql file with structure, and all of its altering file (if exists) - files with 'a_' in the beginning
- after creating structure of DB we have to load the _tmp/z_001_variables_ to load  base data to db
- after loading the base data -> execute files which changes the data in DB - the ones with 'd_' in the beginning

That's the proper scenario I guess. If docker-compose's Dockerfile does that - that's ok, I believe.

@mkowsiak  Could you look at this?

**Comment by mkopsnc** [comment]
This pull request was merged into single single-container-db-alter branch.

Few remarks:

- it should work fine now (when it comes to database population)
- I have removed Demonstrator Dashboard parts completely
- there are small changes related to file ownership (I have reduced number of components that are run/owned by root)
- note that docker-compose part will be heavily affected by OpenShift requirements anyway (no root at all or heavily limited)

**Comment by tzok** [comment]
@agatafilipczak Both `mariadb` and `mysql` Docker images load `/docker-entrypoint-initdb.d/*.sql` files in alphabetical order. If `variables.sql` need to be loaded between `a_*.sql` and `d_*.sql`, then we need to prefix the filename either with `b_` or `c_`, not `z_` as I understood initially. Thanks for the clarification, I will test this approach.

**Comment by mkopsnc** [comment]
@tzok - @agatafilipczak already introduced mapping from our scripts to what is required inside MariaDB (take a look at recent commits). You can read there files are mapped like this:

```
COPY catalog_qt_2/sql/schema/a_001_catalog_qt_db.sql /docker-entrypoint-initdb.d/10-schema.sql
COPY --from=ual /tmp/20-variables.sql /docker-entrypoint-initdb.d/20-variables.sql
COPY catalog_qt_2/sql/schema/d_001_update_variables.sql /docker-entrypoint-initdb.d/30-alter_update_variables.sql
```

**Comment by tzok** [comment]
@mkopsnc But this way the Dockerfile references each file individually. This will require an update of Dockerfile anytime `catalog_qt_2` gets new files in `sql/schema`.

I was thinking of doing it like this:
```Dockerfile
COPY catalog_qt_2/sql/schema/*.sql /docker-entrypoint-initdb.d/
COPY --from=ual /tmp/b_001_variables.sql /docker-entrypoint-initdb.d/
```

**Comment by mkopsnc** [comment]
@tzok - ok, we can go this way; I think we can improve single-container as well; instead of splitting execution of queries into two parts:

```
1.1 create db
1.2 alter db
2.1 add data
2.2 alter db after data are there
```

we can prepare all the scripts and run them in one go.

**Pull request merged**
